In [120]:
import numpy as np

In [121]:
a = [1,2,3,4]
b = [5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [122]:
[a[i]+b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [123]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [124]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [126]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [127]:
arr[:,2:]

array([[3],
       [6],
       [9]])

In [128]:
arr[1:,1:3]

array([[5, 6],
       [8, 9]])

In [129]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [130]:
np.eye(3,3).astype(int).dtype

dtype('int32')

In [131]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [132]:
np.eye(3,3).astype(int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [133]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [134]:
a=np.arange(10)

In [135]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [137]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [138]:
##vector operation

In [139]:
a=np.array([1,2,3])

In [140]:
a**2

array([1, 4, 9])

In [141]:
a*2

array([2, 4, 6])

In [142]:
a+2

array([3, 4, 5])

In [143]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [144]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [145]:
##matrix

In [146]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [147]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [148]:
a

array([[1, 2],
       [3, 4]])

In [149]:
#reshaping
a=np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [150]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 4,  1]])

In [151]:
np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [152]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1],
       [ 1,  2,  3,  4]])

In [153]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [155]:
#copy and vieew
arr=np.array([1,2,3,4,5,6])

In [159]:
b=arr.view()

In [160]:
b[0]=10

In [161]:
arr,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [162]:
c=arr.copy()

In [163]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [165]:
c[0]=11

In [166]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([11,  2,  3,  4,  5,  6]))